name: Publish Python 🐍 distributions 📦 to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-n-publish:
    name: Use PDM to Build and publish Python 🐍 distributions 📦 to PyPI
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          submodules: true

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v3

      - name: Build and Publish distribution 📦 to PyPI
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          echo "__token__:${PYPI_PASSWORD}" > ~/.pypirc
          pdm build
          twine upload --skip-existing --repository pypi dist/*
